unstable_features = true

# Imports
imports_indent = "Visual"
imports_layout = "Horizontal"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Max width
comment_width = 72
enum_discrim_align_threshold = 20
doc_comment_code_block_width = 90
max_width = 90
struct_field_align_threshold = 20

# Indentation
tab_spaces = 2

# Improve my code, please
use_field_init_shorthand = true
use_try_shorthand = true

# Misc
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
match_block_trailing_comma = true
overflow_delimited_expr = false
reorder_impl_items = true
wrap_comments = false
